#!/usr/bin/env python3
"""Embeds the list's font (third_party/fonts/NotoSansMono-Regular.ttf, SIL OFL 1.1, third_party/fonts/OFL.txt) as
a byte array for ImGui's AddFontFromMemoryTTF.  Usage: tools/gen_font.py <out.h>   (build.sh: build/gen/list_font.h)"""
import os, sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
data = open(os.path.join(HERE, "third_party", "fonts", "NotoSansMono-Regular.ttf"), "rb").read()
out = ["// Generated by tools/gen_font.py from third_party/fonts/NotoSansMono-Regular.ttf (SIL OFL 1.1).",
       "#pragma once", "", "#include <cstdint>", "", "namespace edworld::font", "  {",
       f"  inline constexpr std::uint32_t list_font_size{{{len(data)}}};",
       "  alignas(4) inline constexpr std::uint8_t list_font[]{"]
for i in range(0, len(data), 40):
    out.append("    " + ",".join(str(b) for b in data[i:i + 40]) + ",")
out += ["  };", "  }  // namespace edworld::font", ""]
open(sys.argv[1], "w").write("\n".join(out))
