#!/usr/bin/env python3
"""Rasterises the superpower emblems (assets/*.svg, from github.com/Venefilyn/EDAssets, MIT, artwork of Frontier
Developments) into coverage masks for the proxy: src/emblems.h (generated). One byte of coverage per pixel,
HEIGHT tall; the proxy tints them with the superpower's colour.  Usage: tools/gen_emblems.py"""
import io, os, subprocess
import numpy as np
from PIL import Image

HEIGHT = 192
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = ["// Generated by tools/gen_emblems.py from assets/*.svg (github.com/Venefilyn/EDAssets, MIT;",
       "// artwork of Frontier Developments). Coverage masks, one byte per pixel, row-major.",
       "#pragma once", "", "#include <cstdint>", "", "namespace edworld::emblems", "  {"]
for name in ("Federation", "Empire", "Alliance", "Independent"):
    png = subprocess.run(["rsvg-convert", "-h", str(HEIGHT), os.path.join(HERE, "assets", name + ".svg")],
                         check=True, capture_output=True).stdout
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    a = np.array(img)[:, :, 3]
    cols = np.where(a.max(axis=0) > 0)[0]
    a = a[:, cols.min(): cols.max() + 1]
    h, w = a.shape
    var = name.lower()
    out.append(f"  inline constexpr std::uint32_t {var}_width{{{w}}};")
    out.append(f"  inline constexpr std::uint32_t {var}_height{{{h}}};")
    out.append(f"  inline constexpr std::uint8_t {var}_mask[]{{")
    flat = a.flatten()
    for i in range(0, flat.size, 32):
        out.append("    " + ",".join(str(int(v)) for v in flat[i:i + 32]) + ",")
    out.append("  };")
    print(f"{name}: {w}x{h}")
out += ["  }  // namespace edworld::emblems", ""]
open(os.path.join(HERE, "src", "emblems.h"), "w").write("\n".join(out))
